name: Publish Backend
on:
  push:
    branches:
      - prod
jobs:
  release:
    concurrency:
      group: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.PROD_SSH_USERNAME }}
      key: ${{ secrets.PROD_SSH_KEY }}
      port: ${{ secrets.PROD_SSH_PORT }}
      script: cd /home/debian/backend && git checkout prod && git pull && bash start.sh